// Exporta diretamente o objeto categories com os nomes dos arquivos de exercícios por grupo muscular
export const categories = {
  aerobico: [
    'Corrida esteira.gif',
    'Bicicleta.gif',
    'Pular-corda.gif',
    'polichinelos.gif',
  ],
  abdomen: [
    'Abdominal infra solo.gif',
    'Abdominal-cruzado.gif',
    'Abdominal-declinado.gif',
    'Abdominal-infra-nas-paralelas.gif',
    'abdominal-infra-solo2.gif',
    'Abdominal-lateral.gif',
    'abdominal-maquina.gif',
    'abdominal-na-polia.gif',
    'abdominal-remador.gif',
    'abdominal-reto.gif',
    'abdominal-roda.gif',
    'Abdominal-tesoura.gif',
    'Prancha abdominal.jpg',
  ],
  antebraço: [
    'rolo-de-punho.gif',
    'rosca-invertida-com-barra.gif',
    'rosca-martelo-com-halteres.gif',
    'rosca-punho-inversa.gif',
    'rosca-zottman.gif',
    'rusca-punho-com-barra.gif',
    'suspensao-na-barra-dead-hang.gif',
  ],
  bíceps: [
    'chinup-1.gif',
    'Rosca direta barra reta ou W.gif',
    'Rosca martelo.gif',
    'rosca-alternada.gif',
    'rosca-arrastada.gif',
    'rosca-concentrada.gif',
    'rosca-direta-polia.gif',
    'rosca-inclinada.gif',
    'rosca-scott.gif',
    'rosca-simultanea.gif',
    'rosca-spider.gif',
    'rosca-zottman.gif',
  ],
  costas: [
    'Barra fixa supinada.gif',
    'Barra-fixa.gif',
    'Encolhimento ombro.gif',
    'Pull down.gif',
    'Pulley costas.gif',
    'Remada baixa.gif',
    'Remada cavalinho.gif',
    'Remada curvada.gif',
    'Remada serrote.gif',
    'Voador invertido.gif',
  ],
  glúteos: [
    'Agachamento livre.gif',
    'agachamento-barra-postura.gif',
    'agachamento-com-barra.gif',
    'avanco-com-halteras.gif',
    'Coice quatro apoios.gif',
    'coice-no-cabo.gif',
    'Levantamento terra com barra.gif',
    'Ponte com uma perna só.gif',
    'ponte-para-gluteos.gif',
    'Subida no step.gif',
  ],
  ombros: [
    'Crucifixo invertido com halteres.gif',
    'Desenvolvimento Arnold.gif',
    'Desenvolvimento com barra.gif',
    'Desenvolvimento com halteres.gif',
    'Elevação frontal com barra.gif',
    'Elevação frontal com halteres.gif',
    'Elevação lateral com cabo.gif',
    'Elevação lateral com halteres.gif',
    'Elevação lateral inclinada.gif',
    'Elevação lateral na polia.gif',
    'Face pull.gif',
  ],
  panturrilhas: [
    'Elevação  no leg press.gif',
    'Elevação de  barra livre.gif',
    'Elevação de  corpo.gif',
    'Elevação pé na máquina.gif',
    'Elevação sentado com halteres.gif',
    'Elevação sentado na máquina.gif',
  ],
  peito: [
    'Crucifixo.gif',
    'Flexão de braço.gif',
    'Paralelas.gif',
    'Pullover com halteres.gif',
    'Supino declinado (canadense).gif',
    'Supino inclinado.gif',
    'Supino máquina.gif',
    'Supino reto.gif',
    'Voador ou peck deck.gif',
  ],
  pernas: [
    'Afundo.gif',
    'Agachamento frontal.gif',
    'Agachamento goblet.gif',
    'Agachamento hack.gif',
    'Agachamento livre.gif',
    'Agachamento sumô.gif',
    'agachamento-bulgaro.gif',
    'barbell-good-morning.gif',
    'Cadeira extensora.gif',
    'Elevação pélvica com barra.gif',
    'Flexão nórdica.gif',
    'Leg press.gif',
    'Levantamento terra romeno.gif',
    'Levantamento terra sumô.gif',
    'Mesa flexora.gif',
    'Stiff.gif',
  ],
  trapézio: [
    'depressao-escapular-na-puxada.gif',
    'elevacao-halteres-banco-inclinado.gif',
    'encolhimento-com-barra.gif',
    'encolhimento-por-tras-smith.gif',
    'face-pull-na-polia.gif',
    'Levantamento terra.gif',
    'remada-curvada-com-barra.gif',
    'remada-em-pe-com-barra.gif',
  ],
  tríceps: [
    'flexao-diamante.gif',
    'paralelas-para-triceps.gif',
    'rosca-testa-com-barra2.gif',
    'supino-fechado-com-barra.gif',
    'supino-fechado-com-barra.gif',
    'triceps-banco.gif',
    'triceps-coice.gif',
    'triceps-corda-na-polia-alta.gif',
    'triceps-frances-halter-sentado.gif',
    'triceps-invertido.gif',
    'triceps-na-polia-com-barra-reta.gif',
  ],
};
